# Generated by Django 5.1.7 on 2025-10-05 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0003_file_alter_image_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScientificArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто создал",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="content.file",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто изменил",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ScientificArticleTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто создал",
                    ),
                ),
                (
                    "scientific_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scientific_article.scientificarticle",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["tag"],
            },
        ),
        migrations.AddField(
            model_name="scientificarticle",
            name="tags",
            field=models.ManyToManyField(
                related_name="scientific_articles",
                through="scientific_article.ScientificArticleTags",
                to="content.tag",
            ),
        ),
        migrations.CreateModel(
            name="ScientificArticleComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.comment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто создал",
                    ),
                ),
                (
                    "scientific_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scientific_article.scientificarticle",
                    ),
                ),
            ],
            options={
                "ordering": ["comment"],
                "indexes": [
                    models.Index(
                        fields=["scientific_article"],
                        name="scientific__scienti_a52b11_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScientificArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто создал",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.image"
                    ),
                ),
                (
                    "scientific_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scientific_article.scientificarticle",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(
                        fields=["scientific_article"],
                        name="scientific__scienti_dcfbc6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scientific_article", "title"),
                        name="uq_article_image_title",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScientificArticleLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто создал",
                    ),
                ),
                (
                    "like",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.like"
                    ),
                ),
                (
                    "scientific_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scientific_article.scientificarticle",
                    ),
                ),
            ],
            options={
                "ordering": ["like"],
                "indexes": [
                    models.Index(
                        fields=["scientific_article"],
                        name="scientific__scienti_f0d1d7_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="scientificarticletags",
            index=models.Index(
                fields=["scientific_article"], name="scientific__scienti_6b3a1d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scientificarticletags",
            constraint=models.UniqueConstraint(
                fields=("scientific_article", "tag"), name="uq_scientific_article_tag"
            ),
        ),
    ]
