# Generated by Django 5.1.7 on 2025-10-05 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_merge_20251005_1707"),
        ("scientific_article", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=60, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScientificArticleAuthors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="scientificarticle",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="scientificarticlecomments",
            options={"ordering": ["scientific_article", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="scientificarticlelike",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="scientificarticlecomments",
            name="scientific__scienti_a52b11_idx",
        ),
        migrations.RemoveField(
            model_name="scientificarticlecomments",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="scientificarticlelike",
            name="like",
        ),
        migrations.AddField(
            model_name="scientificarticle",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scientificarticle",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scientificarticlecomments",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scientificarticlecomments",
            name="scientific_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="scientific_article.scientificarticle",
            ),
        ),
        migrations.AlterField(
            model_name="scientificarticlelike",
            name="scientific_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="scientific_article.scientificarticle",
            ),
        ),
        migrations.AddIndex(
            model_name="scientificarticlecomments",
            index=models.Index(
                fields=["scientific_article", "created_at"],
                name="scientific__scienti_36290e_idx",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто создал",
            ),
        ),
        migrations.AddField(
            model_name="scientificarticleauthors",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scientific_articles",
                to="scientific_article.author",
            ),
        ),
        migrations.AddField(
            model_name="scientificarticleauthors",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто создал",
            ),
        ),
        migrations.AddField(
            model_name="scientificarticleauthors",
            name="scientific_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scientific_article.scientificarticle",
            ),
        ),
        migrations.AddField(
            model_name="scientificarticleauthors",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто изменил",
            ),
        ),
        migrations.AddField(
            model_name="scientificarticle",
            name="authors",
            field=models.ManyToManyField(
                through="scientific_article.ScientificArticleAuthors",
                to="scientific_article.author",
            ),
        ),
        migrations.AddIndex(
            model_name="scientificarticle",
            index=models.Index(
                fields=["created_at"], name="idx_scient_article_created_at"
            ),
        ),
    ]
