# Generated by Django 5.1.7 on 2025-10-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_tag_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="files/", verbose_name="Файл")),
            ],
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="Изображение"),
        ),
    ]
