# Generated by Django 5.1.7 on 2025-10-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_file_alter_image_image"),
        ("content", "0003_like_unique_user_post_like"),
    ]

    operations = []
