# Generated by Django 5.1.7 on 2025-10-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("display_name", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "otp_expire_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время исчерпания otp",
                        null=True,
                        verbose_name="Время исчерпания otp",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("confirmed", models.BooleanField(default=False)),
                ("subscription_count", models.IntegerField(default=0)),
                ("subscribers_count", models.IntegerField(default=0)),
                ("posts_count", models.IntegerField(default=0)),
                (
                    "avatar",
                    models.ImageField(upload_to="avatars/", verbose_name="Файл"),
                ),
            ],
            options={
                "verbose_name": "Аккаунт",
                "verbose_name_plural": "Аккаунты",
            },
        ),
    ]
