# Generated by Django 5.1.7 on 2025-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(default="", verbose_name="Описание"),
        ),
    ]
