# Generated by Django 5.1.7 on 2025-10-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email_verified",
            new_name="confirmed",
        ),
        migrations.AddField(
            model_name="user",
            name="posts_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_count",
            field=models.IntegerField(default=0),
        ),
    ]
