# Generated by Django 5.1.7 on 2025-10-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_email_verified_user_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default=1, upload_to="avatars/", verbose_name="Файл"
            ),
            preserve_default=False,
        ),
    ]
